// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6zTnXbM7uZIc4LSQ2MRgGvPcfAcmNZGw',
    appId: '1:274877030914:web:36ead5534991e49a21bd1b',
    messagingSenderId: '274877030914',
    projectId: 'my-grid-app-a9d91',
    authDomain: 'my-grid-app-a9d91.firebaseapp.com',
    storageBucket: 'my-grid-app-a9d91.appspot.com',
    measurementId: 'G-HBXFW8SB0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLORquKJXnTyDjrav9ntEDO1-e_I6TzHs',
    appId: '1:274877030914:android:dbc325910b5fcf0d21bd1b',
    messagingSenderId: '274877030914',
    projectId: 'my-grid-app-a9d91',
    storageBucket: 'my-grid-app-a9d91.appspot.com',
  );
}
